### ISSUE TITLE
Error when running Install-DscResourceAddOn

### ISSUE THREAD

**Issue by RiffKhan** [inchara/ShowDscResource#3]
Add-type : Could not load file or assembly

\Documents\WindowsPowerShell\Modules\ShowDscResourceModule\Show-DscResources.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

Windows 8.1 x64
$PSVersionTable.psversion

Major  Minor  Build  Revision

---

5      0      10018  0

**Comment by inchara** [comment]
Looks like it's to do with permission settings., quoting an answer from Stackoverflow link here 
http://stackoverflow.com/questions/18801440/powershell-load-dll-got-error-add-type-could-not-load-file-or-assembly-webdr . Please let me know if this helps?

> If you downloaded the .DLLs from the internet, Powershell by default will not trust them. You can do one of two things here:
> -    Unblock the content. Here's a guide with some elaboration on the problem, but essentially you just need to right-click on the downloaded file, select Properties, and click 'Unblock' in the general tab. You can unblock content directly from powershell by using the Unblock-File cmdlet.
> -    Change your execution policy. This can also allow malicious scripts that you download to run, so be cautious.
> 
> Specifically reviewing and unblocking content you trust seems the better route, especially for your case since you seem like you would only be doing this once and you trust the package.

**Comment by RiffKhan** [comment]
great. that worked! This is a really useful add-on.

**Comment by inchara** [comment]
Good to know it worked! And Thank you! :)
